language: cpp

os:
- linux
- osx

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install qt5; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew link --force qt5; fi

script: qmake && make sub-src-src-cl-pro

after_success: 
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./fet-cl --version; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -zcvf fet-cl-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz fet-cl; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then ls -lR; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then git status; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./fet-cl.app/Contents/MacOS/fet-cl --version; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then tar -zcvf fet-cl-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz --directory=fet-cl.app/Contents/MacOS/ fet-cl; fi

deploy:
  provider: releases
  api_key:
    secure: $FET_ACCESS_TOKEN
  file: fet-cl-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    tags: true
